Homework 02 advanced
BadAllOff/advanced_js_thinknetica pull request #3
Opened 2020-05-18 14:18 UTC by BadAllOff

Additional tasks

2020-05-18 21:28 UTC, arswarog requested changes

2020-05-18 21:28 UTC, arswarog commented on homework 02 advanced/timeConverter.js
> +  const timePeriod = inputTime.match(/[ap][m]/g);
лучше
`inputTime.match(/(am|pm)/g);`
модификатор g здесь идеалогически здесь не к месту, хотя код он особо не изменяет

2020-05-18 21:28 UTC, arswarog commented on homework 02 advanced/timeConverter.js
> +};
обрати внимание что 12:00 am - полночь и 12:00 pm - полдень

2020-05-18 21:28 UTC, arswarog commented on homework 02 advanced/insertNewLinesInSentence.js
> +}
Требуется перенос по словам, так что бы слово на новую строку переносилось только целиком

2020-05-20 05:59 UTC, arswarog approved these changes

2020-05-20 05:59 UTC, arswarog commented on homework 02 advanced/timeConverter.js
> +    const timePeriod = inputTime.match(/[ap][pm]/g);
обращаю внимание что эта регулярка отработает и на "appm"

2020-05-20 06:01 UTC, arswarog approved these changes

2020-05-20 08:17 UTC, BadAllOff commented on homework 02 advanced/timeConverter.js
> +    const timePeriod = inputTime.match(/[ap][pm]/g);
Ах сорри. Я не внимательно просмотрел твой совет с /(am|pm)/g. Поменяю.

2020-05-20 09:29 UTC, merged